### ISSUE TITLE
[DOC] README issues

### ISSUE THREAD

**Issue by ChuckHastings** [rapidsai/cugraph#1112]
## Report incorrect documentation

**Location of incorrect documentation**
cugraph/README.md has a couple of issues

**Describe the problems or issues found in the documentation**

* Link to the latest stable version actually points to cudf
* Link to the latest stable version should be updated to use the new main branch
* Reference to Transition Guide seems dated.  Do we still need this, and if so what should be in the transition guide?

**Steps taken to verify documentation is incorrect**

**Suggested fix for documentation**

**Comment by BradReesWork** [comment]
-     Link to the latest stable version actually points to cudf - fixed in PR 1129

-     Link to the latest stable version should be updated to use the new main branch - fixed in PR 1129

-     Reference to Transition Guide seems dated. Do we still need this, and if so what should be in the transition guide?
 It is a little dated, but will leave it until after 0.16 in case there are issues as me migrate to pattern accelerators.

**Comment by afender** [comment]
The transition guide is outdated but I think we should upgrade it rather than deleting it. It is helpful for users running older versions and has historical value for us to quickly identify API changes between versions.
