### ISSUE TITLE
[BUG] HITS Hub and Auth values are wrong

### ISSUE THREAD

**Issue by BradReesWork** [rapidsai/cugraph#1154]
There appears to be no differences between the HUB and Auth scores - they should be different.  Ans the values do not match networkx

**Comment by ChuckHastings** [comment]
Two things:
* Hub and auth values will be the same if the graph is symmetric.  I see that in both networkx and cugraph/gunrock
* The values do not match networkx due to a documented issue (https://github.com/gunrock/gunrock/issues/760) due to a different normalization strategy.

Updating to the latest gunrock will fix the second issue, as the latest dev branch contains this fix.  I ran a test using the latest gunrock and an asymmetric graph and was able to see that hubs and authorities were different and that they match networkx.

I will put together a PR for this shortly.
