### ISSUE TITLE
[FEA]  Louvain reproducibility

### ISSUE THREAD

**Issue by cjnolet** [rapidsai/cugraph#1258]
There is interest in making Louvain reproducible in some of our example notebooks in https://github.com/clara-parabricks/rapids-single-cell-examples. AFAICT, the popular (CPU-based) `Python` Louvain llibrary that is used in ScanPy is parallel but also accepts a `random_state` argument and is fully reproducible. 

It would be very useful if we were able to do this in cugraph's implementation as well.

**Comment by ChuckHastings** [comment]
Define reproducible for me.

Our Louvain implementation does not do a random permutation of the vertices (which the serial version does).  I haven't reviewed the ScanPy implementation but could check this out.

Because we don't do a random permutation, I believe the results of our implementation are deterministic.  When we shift to MNMG it appears to be deterministic for a given input and 2D cluster configuration.

**Comment by cjnolet** [comment]
Tagging @avantikalal for further info, if needed. 

Update: We discussed this briefly offline and believe Chuck has a potential solution here, by allowing potential ties to be broken with a fixed random seed when reproducibility is desired.
