### ISSUE TITLE
Line graph implementation - Python [FEA] 

### ISSUE THREAD

**Issue by vymao** [rapidsai/cugraph#1262]
It would help very helpful if cugraph could support line graph generation, given a graph, in a similar manner to NetworkX.

**Comment by BradReesWork** [comment]
@vymao That has been on our roadmap for a while but keeps getting bumped.  Now that someone is asking for it, I will work it into one of the upcoming releases.

**Comment by iliathesmirnov** [comment]
Hello everyone,

I am new here and would like to contribute. 

The idea of my proposed approach for finding the line graph L(G) of a graph G (this is for an undirected graph only) is to compute

Adjacency matrix of L(G) = N(G)^T N(G) - 2 * I

where N(G) is the incidence matrix of G (it has (# vertices) rows and (# edges) columns), 
           N(G)^T is its transpose, and 
            I is the identity matrix.

Since both N(G) and I are sparse matrices, they should be stored as such and cuSPARSE should be used to compute the product.

The adjacency matrix of L(G) can then be stored in one of the sparse formats derived from the GraphViewBase class (COO, CSR or CSC).

However, as far as I can find, there is no incidence matrix implementation yet?

So, my questions are

1) Is there actually an implementation of the operation of finding an incidence matrix. If not, is there a reason why it was decided not to include this, or is it just a matter of it not being done yet? I would be happy to write an implementation if the latter is true.

2) Does the above high-level proposal for computing L(G) sound reasonable?

Thank you,
Ilia Smirnov

**Comment by afender** [comment]
Hi @iliathesmirnov,

Thank you for contributing! 

We do not have the incidence matrix at this time for the simple reason that it has not been implemented yet. The line graph is a great motivation for adding it. Intuitively, it should be possible to retrieve the edge indexes from the CSR format and populate the incidence matrix for every vertex in parallel.

The proposal sounds reasonable in the sense that it will give the correct result. Performance and scalability wise, N(G)^T N(G) should be fast in cusparse but remains a sparse matrix multiplication operation. So, if matrices are really large, this will be a challenge. I would estimate the limit to be between a couple of dozens and a hundred thousand vertices depending on density on a high end GPU. There are a few algorithms (Roussopoulos, Lehot, Syslot) for building a custom solution but haven't reviewed all the literature at this time https://en.wikipedia.org/wiki/Line_graph#Algorithms

Thanks,
Alex

**Comment by BradReesWork** [comment]
work on line graph is going to be captured in a new issues
