### ISSUE TITLE
[ENH] Add a `datasets` API and cleanup existing datasets

### ISSUE THREAD

**Issue by rlratzel** [rapidsai/cugraph#1348]
CuGraph could benefit from a new `datasets` API that allows users to easily create Graph objects from pre-defined datasets.  Currently, users have to read a file using cuDF to create an edgelist, then create a Graph instance from the edgelist.  This is a multi-step process that is very common, yet not always easy to remember.  Streamlining this very common process will benefit users as well as our tests and benchmarks.

The datasets directory also needs to be cleaned up a bit and the README updated.

* Consolidate redundant subdirs and remove unused: “ref”, “test/ref”, “highbench_small/1”
* Update README (if necessary)
* Update download script (if necessary)

For all of the above, the Python and C++ test and benchmarks need to be checked to see if they are referencing any dataset that might be a moved or renamed as part of the cleanup.

**Comment by betochimas** [comment]
Some tasks for this project:
- [ ] Write Dataset and Metadata class
- [ ] Write datasets/__init__.py and meta-data files for each dataset
- [ ] Remove unused datasets across all layers of cugraph
- [ ] Testing
- [ ] Update docstrings
- [ ] Update notebooks
- [ ] If necessary, write notebook and/or section in html docs demoing API

**Comment by oorliu** [comment]
I fleshed out the `__init__` method for `MetaData` to open a JSON file and store its info.

**Comment by betochimas** [comment]
@cjnolet @dantegd @wphicks 
As of now, these are current requirements for the `datasets` API. The issue addressing the first set of changes is #2351 
We appreciate any feedback as we work on making this tool compatible across cugraph and others

**Comment by betochimas** [comment]
In today's sync, we agreed on ensuring that the metadata and configuration `.yaml` files are input-only (user provides them if they want to load custom datasets or modify configs) and are not writeable. The path to the datasets will then be stored as an attribute to the `datasets` object, and will not be part of the metadata in the `.yaml` file. We introduced `load_all`, a utility function outside of `datasets` class that fetches all datafiles from the metadata files from within the metadata directory. This can be used for validation, and downloading dataset all together

**Comment by betochimas** [comment]
Status update:

- get_path returns the path to where the dataset is stored in the form of a PosixPath object, if downloaded. Otherwise will return None, indicating that the dataset could not be found
- load_all is a utility function that loads all metadata yamls from within metadata and downloads them if missing. Custom metadata yamls can be dropped in that directory in addition to the defaults.
- While a default datasets_config.yaml specifies default storage location and whether to automatically fetch, these properties shared across the Datasets instances can be overwritten if set_config is called with another configuration yaml file. Like load_all, this is not a method from within the Datasets class.
- An environment variable like DOWNLOAD_DIR, IS_FETCH could be used to overwrite fetch/download_dir settings, similar to a custom config yaml. If so, the ranking of priority would be:
- (Highest to Lowest) API call to set_config -> Environment Variable defaults -> datasets_config.yaml defaults
- The "path" field within the individual metadata yamls has been moved to be an attribute of a Dataset instance
- This PR is close to review, and while using .csv files only, will serve as the basis for future Datasets API work
- Notebooks PR by @oorliu is after #2351 is closed, and significant progress has been made on that subtask
- Docstrings PR is still a WIP, and will uniformly revamp the docstrings with cleaner demo friendly examples

**Comment by oorliu** [comment]
As of now, the following datasets are supported by the `datasets` API:
* karate-data.csv
* dolphins.csv
* netscience.csv
* polbooks.csv
* cyber.csv

**Comment by oorliu** [comment]
**Status Update:**

* `get_path` returns the absolute path to where the dataset is stored. It is set when the dataset object reads in an edge-list. If this step has not been done, it will raise a `RuntimeError`
* `set_download_dir` is a external helper method that allows a user to specify where to downloaded datasets to
* `get_download_dir` can be used to view what the current download location is set to
* `set_config` is an external helper method where a user can specify a custom `config.yaml` file, which will be read in and override any current settings of the API. Ex. download directory, default fetch behavior, etc.
* The API now supports the creation of directories, as well as nested directories. If I call `set_download_dir` and use `/path/that/doesn't/exist`, the API will attempt to create that path when downloading datasets.
  * There is currently an effort to specify if directory creation should be allowed through the configuration file.
* The API will check for a `RAPIDS_DATASET_ROOT_DIR` environment variable upon initialization. This is another way of setting the download directory of the datasets API.


**The download location hierarchy:**

1. The user calls `set_download_dir("some/directory")`
2. The environment variable `RAPIDS_DATASET_ROOT_DIR` is set
3. The user calls `set_config("config_file_location")`
4. Download to the user's home directory; specifically `<HOME>/.cugraph/datasets`

**Comment by rlratzel** [comment]
#2367 closes this
