### ISSUE TITLE
[EPIC] Optimize renumbering

### ISSUE THREAD

**Issue by Iroy30** [rapidsai/cugraph#1451]
The current renumbering performs cudf/dask_cudf merges for unrenumbering and re-renumbering. Single column renumbering can be optimized using local unrenumbering to make it faster instead of merge operation

**Comment by rlratzel** [comment]
From @seunghwak - to help address this:
https://github.com/rapidsai/cugraph/blob/branch-21.12/cpp/include/cugraph/graph_functions.hpp#L199
https://github.com/rapidsai/cugraph/blob/branch-21.12/cpp/include/cugraph/graph_functions.hpp#L229
https://github.com/rapidsai/cugraph/blob/branch-21.12/cpp/include/cugraph/graph_functions.hpp#L298
We should unrenumber using these C++ functions instead of relying on dask-cudf.

**Comment by ChuckHastings** [comment]
For integer vertex columns we can address this in the new C API.

**Comment by ChuckHastings** [comment]
I believe that all of the plumbing exists in C++ to handle this properly for int32 and int64 types.  IMO, there are two options here:
* The C API *already* does this for int32 and int64 types, we can python implementations to the C API and get this for free
* We can modify the NumberMap.py implementation to call the C++ mechanisms which would get us all of the algorithms doing this now, at the cost of some throw away code

I bumped this out to 22.04, but 22.06 might be a better target.  Alternatively, we could close this in favor of migrating everything to the C API.
