### ISSUE TITLE
[FEA] All paths between two vertex sets

### ISSUE THREAD

**Issue by afender** [rapidsai/cugraph#1542]
Develop an algorithm that returns all paths between two sets of vertices.  This can start as all paths between a pair of vertices and then be expanded

**Comment by ChuckHastings** [comment]
To clarify... I assume you mean:
* Paths without cycles
* Perhaps an optional minimum and maximum path length

Naively in serial (to be sure we understand the objective):

1. For each source vertex, create a path of length 0 containing the vertex, add to the active path list
2. While the active path list is not empty, take the first element from active path list and do the following
a. Take the vertex for the end of the path
b. For each edge incident on that vertex check to see if the vertex is already on the path, if so skip this edge
c. If the edge was not in the path, add the neighbor vertex to the end of the path.  If the neighbor vertex is in the destination set, add the path to the published answers.  Otherwise append the path to the active path list

**Comment by BradReesWork** [comment]
replaced by issue in graph_dl
