### ISSUE TITLE
[QST] Result of Leiden algorithm being different for renumbered and non-renumbered graph

### ISSUE THREAD

**Issue by jmatak** [rapidsai/cugraph#2263]
Having a graph represented by the `edgelist` that has a structure like the following:
```
1,0
1,3
2,1
4,0
4,2
```
Vertices are having labels in the range [0, V - 1] therefore they are kind of renumbered already. Loading a graph with `renumber=True` and `renumber=False` gains two completely different results for the Leiden `(cugraph.leiden(G)) algorithm` call. What is the reasoning behind this?

**Comment by jnke2016** [comment]
@jmatak . I ran Leiden with your datasets using both renumbered and unrenumbered data and below is the result.
```
renumbered data results (vertices 4, 2, 0 belong to partition 0)
parts is 
    partition  vertex
0          1       1
1          0       4
2          0       2
3          0       0
4          1       3
mod is 
 0.07999999821186066

Unrenumbered data results (vertices 4, 2, 0 belong to partition 1)
parts is 
    vertex  partition
0       0          1
1       1          0
2       2          1
3       3          0
4       4          1
mod is 
 0.07999999821186066
```
Both results are correct and the label assigned to each partition is arbitrary. The grouping of vertices is the most important thing, not the cluster's label. It is also important to notice that Leiden along with several other algorithms like Louvain are approximation algorithms therefore, they can legitimately generate different results that are valid.

**Comment by jmatak** [comment]
@jnke2016 Thanks for checking it out, I fully understand the reasoning of algorithms being non approximative and generating different results, however in the example below two results have the same modularity scores (expected since the structure is similar), which is not the case for my case. What version of cuGraph are you running?

```
The unrenumbered graph generates completely different result.
0       0          0
1       1          1
2       2          2
3       3          3
4       4          4, -0.35999998450279236)

The renumbered version generates the similar result as above
0          1       1
1          0       4
2          0       2
3          1       0
4          1       3, 0.07999999821186066)
```


Furthermore here is the script I am using with cuGraph 22.02:
```
import cudf
import cugraph

def call_algorithm(G):
    result = cugraph.leiden(G)
    print(result)

# Read data into a cuDF DataFrame using read_csv
gdf = cudf.read_csv("graph_data2.csv", names=["src", "dst"], dtype=["int32", "int32"])

# Create a non-renumbered graph
G1 = cugraph.Graph(directed=True)
G1.from_cudf_edgelist(gdf, source='src', destination='dst', renumber=False)

# Create a renumbered graph
G2 = cugraph.Graph(directed=True)
G2.from_cudf_edgelist(gdf, source='src', destination='dst', renumber=True)

# Compare the results of algorithm run
call_algorithm(G1)
call_algorithm(G2)
```

**Comment by ChuckHastings** [comment]
Our version of Leiden is based upon our implementation of Louvain, rather than an independent implementation.  A clean GPU version of Leiden is on our road map, but will require some work trying to determine how to find adequate parallelism without losing correctness of the results.

Because our version of Leiden is based upon our version of Louvain, it is limited to working on undirected graphs.  I believe this is causing the behavior that you are seeing.  Our version of Louvain computes the change in modularity for all possible vertex moves and picks the best one for each vertex and moves them all at once.  In order to guarantee convergence, we limit moves to transition to higher numbered clusters in odd iterations and lower numbered clusters in even iterations.  In a symmetric (undirected) graph, if an edge connects vertices u and v, `either` vertex u `or` vertex v will move in an iteration, not both.  In every iteration within a symmetric graph, if there is a move which will improve modularity there will be an edge that will permit it regardless of which direction we are allowing in this iteration.  In an asymmetric (directed) graph, it's possible (given an arbitrary numbering of the vertices in the graph), that there are no possible moves in an iteration because the only move that would improve modularity is in the wrong direction.  I believe this is what is happening here.

When we add full support for Leiden we will address this shortcoming in handling of an asymmetric (directed) graph.  It seems likely that in a large enough graph you would be unlikely to see this issue, although that's purely intuition.

**Comment by jnke2016** [comment]
@jmatak Adding to what was mentioned by @ChuckHastings , an exception is supposed to be raised when attempting to run either Leiden or Louvain with a directed graph. PR #2267 updates the docstrings and raises the appropriate exception

**Comment by jmatak** [comment]
Thank you @jnke2016 and @ChuckHastings for the help! I  should have presumed that the problem might lay in the graph directedness. After implementing my code in C++ API, everything seems to be working for undirected graphs. Looking forward till directed graphs are supported :smile:
