### ISSUE TITLE
[ENH] `datasets` API: Creating an Edgelist

### ISSUE THREAD

**Issue by oorliu** [rapidsai/cugraph#2351]
Milestone for #1348

Implement a method within the `dataset` module to download and store datasets given a YAML metadata file. Once the dataset is stored locally, implement `get_edgelist` to read-in an edgelist.

Some design elements to consider:
- Default path to download files to '/datasets/..'
- Giving the user the ability to override the download path.
- *If doing the above, the location where the custom path is stored.

**Comment by oorliu** [comment]
Status update:

- `get_edgelist()` works for the most part. The "path" field within the `.yaml` file will direct `datasets.py` where to read in the datafile. If it cannot find the file, it will fetch from the "url" specified within the metadata.
  - Raises RuntimeError if `fetch=False` and datafile does not exist.
- `get_graph()` will check for the existence of an edgelist. If not found, it will call `get_edgelist()` and pass along the `fetch` variable.
- **Next step:** provide `datasets_configuration.yaml` to specify default storage location when fetching from the web. The location that a datafile is written to will be updated in "path" so `datasets.py` will reuse local datasets.
  - Suggestion: Writing a method to load all data available from `./metadata`, or to verify local data integrity?

**Comment by betochimas** [comment]
Status update:
-  `get_path` returns the path to where the dataset is stored in the form of a PosixPath object, if downloaded. Otherwise will return None, indicating that the dataset could not be found
- `load_all` is a utility function that loads all metadata yamls from within `metadata` and downloads them if missing. Custom metadata yamls can be dropped in that directory in addition to the defaults.
- While a default `datasets_config.yaml` specifies default storage location and whether to automatically fetch, these properties shared across the Datasets instances can be overwritten if `set_config` is called with another configuration yaml file. Like `load_all`, this is not a method from within the Datasets class.
- An environment variable like DOWNLOAD_DIR, IS_FETCH could be used to overwrite fetch/download_dir settings, similar to a custom config yaml. If so, the ranking of priority would be:
- (Highest to Lowest) API call to set_config -> Environment Variable defaults -> datasets_config.yaml defaults
