### ISSUE TITLE
[DOC] update `SOURCEBUILD.md` to match the latest build procedure

### ISSUE THREAD

**Issue by rlratzel** [rapidsai/cugraph#2500]
We need to ensure `SOURCEBUILD.md` covers building `pylibcugraph`, when to use `build.sh` vs. manually running individual lower-level commands, etc.

do as part of #2663

**Comment by naimnv** [comment]
I came across the following issues - 
# Test failure
**cugraph/cpp/build$ make test**
The following tests FAILED:
         41 - UNIFORM_NEIGHBOR_SAMPLING_TEST (Failed)
         58 - CAPI_UNIFORM_NEIGHBOR_SAMPLE (SEGFAULT)
# No gtest folder under cugraph/cpp/build (mentioned under **Run tests** section)
gtests/GDFGRAPH_TEST		# this is an executable file

**Comment by rlratzel** [comment]
@alexbarghi-nv has a concise set of instructions that should also be included as an option. Some cugraph devs use this procedure, and I suspect it will start to be more common. This could also be included in a section describing the advantages of using a dev container:

> 1. Pull the latest CUDA 11.5 rapids development docker image
> 2. Start a docker container from the image
> 3. Run conda env update using the yaml files included in cugraph
> 4. Use build.sh to build cugraph as usual

**Comment by GregorySchwing** [comment]
Any updates on this?  Could a rapids dev post step by step instructions for building from source?  I tried this without success

sudo docker run --gpus all --ipc=host --ulimit memlock=-1 --ulimit stack=67108864 --rm -it -p 8888:8888 -p 8787:8787 -p 8786:8786  rapidsai/rapidsai-dev:22.12-cuda11.5-devel-rockylinux8-py3.8
cd ../..
git clone  https://github.com/rapidsai/cugraph.git
cd cugraph
git fetch --all
git checkout branch-22.12
conda env update --file conda/environments/cugraph_dev_cuda11.5.yml --prune -y
conda activate cugraph_dev
bash ./build.sh

Build output in #3221

**Comment by GregorySchwing** [comment]
Final procedure (working):

sudo docker run --gpus all --ipc=host --ulimit memlock=-1 --ulimit stack=67108864 --rm -it -p 8888:8888 -p 8787:8787 -p 8786:8786 rapidsai/rapidsai-dev:22.12-cuda11.5-devel-rockylinux8-py3.8
cd ../..
git clone https://github.com/rapidsai/cugraph.git
cd cugraph
git fetch --all
git checkout branch-22.12
**conda env update --file conda/environments/cugraph_dev_cuda11.5.yml --prune -y**
bash ./build.sh

Not sure if the bolded is neccessary since I didn't use the conda env.

Things I learned: 
1.) cugraph-ops is located if you use the rapids dev container.
2.) Ensuring the rapid dev cugraph version and the branch of cugraph match is necessary.
3.) Possibly: there are dependencies installed by conda env update which are missing from the rapids dev container.  (will verify by repeating process without conda env update)
