### ISSUE TITLE
[FEA] Support adding `edge_ids` to PG in add_edge_data

### ISSUE THREAD

**Issue by VibhuJawa** [rapidsai/cugraph#2565]
**Describe the solution you'd like and any additional context**

Currently in PG [add_edge_data](https://github.com/rapidsai/cugraph/blob/cc057589799366b44eacf8b6f4a335223e4927c2/python/cugraph/cugraph/structure/property_graph.py#L478-L505)  we assign `edge_ids` on our own and the user cant add its own if they want to. 

**Context**

This feature is useful especially when converting b/w a graph from external  framework like DGL to cuGraph.  I think it might be worth-while to support adding `edge_ids`  directly in the below API so that the users can cleanly b/w frameworks. 

  

**Proposed API**
```python
   def add_edge_data(self,
                      dataframe,
                      vertex_col_names,
                      edge_id_col_name=None,
                      type_name=None,
                      property_columns=None
                      ):
        """ 
 ```

**Comment by VibhuJawa** [comment]
> What happens if the user provides edge IDs for the initial add_edge_data, but then does not for a future add_edge_data, and vice-versa?

I think we should raise an error and ask the user to provide them and let them in the control of it .

**Comment by rlratzel** [comment]
> > What happens if the user provides edge IDs for the initial add_edge_data, but then does not for a future add_edge_data, and vice-versa?
> 
> I think we should raise an error and ask the user to provide them and let them in the control of it .

We had further discussion on this offline:
<hr>
@rlratzel:
I'm tempted to say maybe we don't support either case 1 or case 2?  Instead, remember what the user first provided (auto-IDs, or custom IDs), then enforce that for subsequent calls.

For case 1, it seems like we're assuming the user will want sequential IDs starting after the last max ID value, and we'll silently make that happen.  I'm wondering if the reason they provided custom IDs in the first place is because they need something different, and maybe they forgot to specify the edge ID column on the next call as a mistake?  If that's the case, this could be a frustrating UX.  I don't know this for certain though.

Case 2 seems odd/unlikely (maybe?) Unless it's obvious that PG requires edge IDs internally, then the user may think the edges they added w/out specifying IDs just don't have them, and the ones they added w/ IDs are the only ones that do, which might be what they want/need for some reason.  I'm also just guessing here.

Either way, it seems safest to raise an exception if the user changes course (ie. provides IDs/expects generated IDs) in between calls.  But again, I don't know if supporting case 1 and not supporting case 2 is really what most of our users would expect, and if so, maybe it's worth the extra effort.
<hr>
@VibhuJawa:

> Case 2 seems odd/unlikely

Completely agree that this case is  unlikely.

> Case 1:

I think its a UX choice we have to make.
We can hand over the responsibility of adding edge ids to the user and fail loudly if not.
The benefit of adding it ourselves is its easier UX but we are trading that off with users shooting them selves in the foot
<hr>
@eriknw:

I'm fine with any option.  raising on mixed-use is the most conservative--we can add any other behavior as needed.  I'll update the PR
