### ISSUE TITLE
[FEA] Update CI build to only run algorithm notebooks

### ISSUE THREAD

**Issue by BradReesWork** [rapidsai/cugraph#2622]
**Describe the solution you'd like and any additional context**
Once the notebook folders are updated 

#2612 
#2611
#2610 

Update CI build to only run notebooks under "algorithms" and not all notebooks.

https://github.com/rapidsai/cugraph/blob/bbb54c7404de7d93612515530911c7abd9df3d9d/ci/gpu/test-notebooks.sh#L21
NOTEBOOKS_DIR=${WORKSPACE}/notebooks

---
_For Developers below this line_

  - [] Code passes CI
  - [] Code uses Graph Primitives
  - [] Code in C++/CUDA layer
  - [] Code in C layer
  - [] Code in pylibcugraph Python layer
  - [] Code in cugraph Python layer
  - [] Documentation
  - [] Test cases at each layer (for MG tests, a note in the PR description indicating the new/existing MG tests were run and passed)

**Comment by rlratzel** [comment]
I don't think we should change the top-level `test-notebooks.sh` script for this, since that will introduce a separate skipping mechanism that we'd have to maintain. I'd rather extend [the current tool](https://github.com/rapidsai/cugraph/blob/branch-22.10/ci/gpu/notebook_list.py) that we use to enumerate NBs so that it understands if an entire directory should be skipped, perhaps by looking for the presence of a file (eg. `SKIP_CI_TESTING`).  That way, it's easy to see if a directory will be skipped or not just by browsing the source tree, and it includes a message in the logs saying it's being skipped so there's no surprises.

cc @ChuckHastings since he worked on `notebook_list.py`

**Comment by rlratzel** [comment]
Adding more context...

The longer-term plan was to run a subset of NBs for CI (ie. what this issue is describing), but run the full set of NBs on a nightly or weekly basis so we get some regular automated coverage without slowing down CI too much.  The idea was to just run the same script, perhaps with different args for the different run "modes" (CI, nightly, weekly, etc.).  Ideally the arg to this script would simply get passed to `notebook_list.py` to tell it what should be run based on the run mode, so we have a single tool that defines the skip/run policy.

**Comment by BradReesWork** [comment]
@rlratzel by making the top level be "/notebooks /algorithms"  we can either drop the "skip" tool or limit it to just items in the algorithm section.  The other sections "demo" and "benchmarks" should never be run as part of CI.

Now we should run the benchmark notebooks weekly, but that is outside of CI
