### ISSUE TITLE
[FEA] create a validation suite as a standalone [TEST]

### ISSUE THREAD

**Issue by afender** [rapidsai/cugraph#265]
The goal is to decouple python testing from python setup and cugraph env as much as possible. 
After these changes, NetworkX and others should not be a dependency of cugraph anymore. It should be only needed for pytest.
We need to provide a convenient way for the user to get test dependencies and run tests.

There different ways to achieve this. The first step is to review the options and identify the most appropriate. I think a Notebook solution should be considered as well.

**Comment by afender** [comment]
We probably want to do this in 0.11 as part of the refactoring release

**Comment by rlratzel** [comment]
I like this issue, and this validation suite will allow us to pull in dependencies needed for proper validation that shouldn't be hard runtime dependencies for cugraph itself (much like notebooks, hence the suggestion, I'm assuming).

Questions:
* I'm assuming the goal is to ensure compatibility and performance expectations with NetworkX?  Or, are there additional validation steps that should be included that aren't covered in regular functional and performance testing?
* Should the new benchmarks in `<cugraph root>/benchmarks` cover this, or do we want those to be runnable without extra dependencies?
* Should we focus on a notebook-based solution from the start, since those already have an assumption of extra deps that may need to be installed?  We can make a notebook that performs a pass/fail type of check and would catch regressions using the automation CI uses.
* [not a question] The new benchmarking infrastructure in `<cugraph root>/benchmarks` has the ability to check for regressions as well as functional correctness, so we can also use that here as an option.
* Do we need to think about our C++ API here too, or is a python-based solution adequate (since it'll eventually hit the same code paths)?

**Comment by rlratzel** [comment]
With the recent addition of support for the `RAPIDS_DATASET_ROOT_DIR` env var (as documented [here](https://docs.rapids.ai/maintainers/datasets/#running-tests-that-use-datasets)), the current cugraph python tests can be used as a standalone validation suite (ie. the source tree is no longer required). 

There are a few steps that need to be done in order to do this, and the following assumes a RAPIDS `runtime` [docker image](https://hub.docker.com/r/rapidsai/rapidsai) (conda-installed RAPIDS packages, no source code) - different environments may require different packages:
* Install test dependencies:
  * `conda install python-louvain rapids-pytest-benchmark`
* Download the datasets:
  * [This script](https://github.com/rapidsai/cugraph/blob/branch-0.19/datasets/get_test_data.sh) can be used to download the correct datasets.
* Set `RAPIPDS_DATASET_ROOT_DIR` to the location of the downloaded datasets.
* Run the tests using pytest, specifying the path to the cugraph install containing the tests package:
  * `pytest /opt/conda/envs/rapids/lib/python3.8/site-packages/cugraph/tests`
