### ISSUE TITLE
[QST] Accept unsigned IDs?

### ISSUE THREAD

**Issue by darabos** [rapidsai/cugraph#2670]
#2337 has added a restriction in `simpleGraph.py` to only accept `int32` and `int64` IDs without renumbering. My code had `uint32`. 😭 The restriction could be easily relaxed to allow unsigned IDs, and it was working for me. Would it be okay to send a PR for this, or is there some concern about unsigned IDs?

Thank you!

**Comment by BradReesWork** [comment]
@darabos yes, please send in a PR that adds support for unsigned ints

CC  @jnke2016

**Comment by jnke2016** [comment]
Hi @darabos. Thanks for raising this up. What is the motivation behind setting `renumber=False`?

**Comment by darabos** [comment]
> Hi @darabos. Thanks for raising this up. What is the motivation behind setting `renumber=False`?

I already have a contiguous vertex ID space. Getting the results out of cuGraph is easier without renumbering. Renumbering itself sounds expensive so I thought it was better to skip it if we can.

You can see what we're doing at https://github.com/lynxkite/lynxkite/blob/main/sphynx/python/cugraph_pagerank.py and a few other files in the same directory. We just started using cuGraph, so if we're doing it wrong, let us know.

**Comment by jnke2016** [comment]
Hi @darabos . Upon reviewing your PR and considering the effect on our internal code base, this PR will likely break if a `uint` were to be passed to our C++ API which only support `int32` and `int64`. However, we came up with few suggestions that may satisfy you requirements
- You could enable renumbering: Python renumbering of integer data on a single GPU should be relatively inexpensive.  C++ renumbering is also triggered by this flag and makes the graph computations more efficient as the vertices are ordered in an optimal manner (not just from `[0, num_vertices[`).  This is the easiest change.
- You could switch your code to generate an `int32/int64 `instead of `uint32/uint64`
- If the data meets the above criteria you could convert the `cudf.Series/DataFrame` from the `uint32/uint64` to `int32/int64` (pretty fast, just costs extra GPU memory) right before calling the graph.
- You could somehow coerce the types (would require some tricky python programming, I suspect) to `int32/int64`.  In C++ you could just cast the data as int32/int64 and use the data since the C++ renumbering would then do the right thing.
- You could build your own copy of `cugraph` from source and add `uint32/uint64` variations.  I suspect we will eventually make this easier, right now it would be pretty tricky and obviously the hardest of the options.

**Comment by darabos** [comment]
Thanks for the detailed answer, @jnke2016! It's very helpful. For our upcoming release we're doing the conversion on the `cudf.DataFrame` before creating the graph. But I'll run some benchmarks with renumbering later, maybe it's fine.
