### ISSUE TITLE
[FEA] Handling Disconnected Vertices in SSSP

### ISSUE THREAD

**Issue by MurrayData** [rapidsai/cugraph#303]
I've been evaluating cuGraph in RAPIDS 0.7, on a number of real world applications with great results on acceleration. It's really fast. Well done team.

Using Spatia and RAPIDS, I converted UK Ordnance Survey's Open Roads geospatial dataset into a weighted graph of the road network in Great Britain on distance between nodes, loaded it into a cuDF dataframe and then ran SSSP on it. I've shared a sample notebook and links to the data [as a Github repository Github](https://github.com/MurrayData/RapidsGBRoadGraph) As open data derived work, this can be freely shared and exploited, subject to the terms of OGL.

It looks like this when overlaid on top of a topological map. The vertex highlighted in yellow is our lab at the University of Liverpool.

![roxby](https://user-images.githubusercontent.com/8914493/58367196-2fb3f480-7ed4-11e9-887d-1dba5e816d53.png)

Great Britain consists of many islands, some of which are connected to the mainland by bridge and tunnels, but others not. I could include ferry routes in the graph, but many of the remote Scottish Islands have not scheduled service. However, they do have local roads. This means that some parts of the graph are disconnected.

![image](https://user-images.githubusercontent.com/8914493/58368260-7c9ec780-7ee2-11e9-8171-46248b667a47.png)

I observed that in such cases, cuGraph SSSP returns the largest possible value of the weights field type.

![image](https://user-images.githubusercontent.com/8914493/58368252-57aa5480-7ee2-11e9-9290-dc65c7df9f2a.png)

In this case I'm using FP64 dtype for the weights, so it returns 1.7976931348623157e+308. If I change the weight field dtype to FP32, it returns 3.4028235e+38.

When I filter the resultant DataFrame, it returns the correct results for the connected nodes.

![image](https://user-images.githubusercontent.com/8914493/58368314-3f870500-7ee3-11e9-8f94-7c7f8d5032fb.png)

Returning a negative value would not work as some graphs legitimately have negative weighting for penalties. I am wondering if returning None or NAN may work as you can test for it and it isn't dependent on the weight field dtype.

**Comment by afender** [comment]
Pretty cool work in https://github.com/MurrayData/RapidsGBRoadGraph !! 

Thanks a lot for your feedback and suggestions. That makes sense and we will return NaN/None values for unreachable vertices in SSSP in the next release. 

We will also take a closer look at disconnected graph support in cuGraph in general (#305). I hope this is going to be helpful for your projects. 

Finally, the team is working on SSSP right now to improve the current solution by also returning predecessors (#292). We would be happy to try a use case or data set that is relevant to your applications and leverages predecessors if you want to.

**Comment by afender** [comment]
+ @pgera : this is the issue related to the new SSSP output

**Comment by MurrayData** [comment]
Thanks @afender. The issue of disconnected vertices can also happen as a result of pre-filtering the dataframe prior to bulding the graph. As an example, I've taken a very common retail scenario as an example in calculating drive time to nearest store which I will present in the demonstration I'm presenting tomorrow at NVIDIA's Enterprise Innovation Day in Manchester.

I have attached average drive times in seconds on edges using the UK Department for Transport open data, so we have a time weighted, rather than distance weighted, road graph. Then for 100 store locations we have filtered to grid squares on 70 miles around the store (UK maximum drive speed), using a cuDF query, and performed the graph analysis on those as we are only interested in up to 1 hour. 

I noticed that the graph from the filtered out edges also return FP max.

![image](https://user-images.githubusercontent.com/8914493/58547073-a0258300-81fe-11e9-85ef-7202bf37c502.png)

It is amazingly fast though.

![image](https://user-images.githubusercontent.com/8914493/58547088-a7e52780-81fe-11e9-9763-5faab45b66d4.png)

Resultant output displayed in GIS

![image](https://user-images.githubusercontent.com/8914493/58547130-bdf2e800-81fe-11e9-8c66-9b0f4ea9c2d9.png)

 I've made 2 notebooks, with data, available on Github:

* GB Nodes (the one above)
* Santa Clara County

https://github.com/MurrayData

**Comment by afender** [comment]
Hi @MurrayData, RapidsSantaClaraRoadGraph is pretty impressive too!

#341 added `filter_unreachable(df)`, a new function to return a filtered data frame with only reachable vertices. This function works for SSSP (any FP precision) and BFS. 

Notice that, after considering several options, we did not change the output of SSSP directly because it allows : 
- accessing the shortest distance of any vertex in O(1). In comparison, the filtered output requires a binary search or using a hash map. 
- natively running min and sort operations on it. In comparison, NaN may limit this.
- preserving the previously released API.

In addition to the filtering feature, the next version of cuGraph (0.8) will provide a completely new and improved SSSP implementation on the GPU. While the current version uses a semiring algorithm, the new one is based on a frontier approach developed by @pgera. This allows returning the direct predecessor of each vertex in addition to the distance and potentially reconstructing any shortest path. Our preliminary results also show that it is faster for most graphs. Please let us know if you get a chance to try it!

**Comment by pgera** [comment]
I just tested this notebook, and here are the timing measurements from the comments earlier in the thread for add_edge_list and sssp respectively on a v100:

Old SSSP:
CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 1.93 ms
CPU times: user 1.73 s, sys: 612 ms, total: 2.34 s
Wall time: 2.35 s

New SSSP:
CPU times: user 4 ms, sys: 0 ns, total: 4 ms
Wall time: 4.87 ms
CPU times: user 888 ms, sys: 240 ms, total: 1.13 s
Wall time: 1.13 s

\>2x speedup for sssp. The increase in add_edge_list's time is likely due to the additional validation checks that we added for detecting negative weights.

**Comment by afender** [comment]
Closing old issues. `filter_unreachable` was added in 0.8.
