### ISSUE TITLE
[FEA] Status of disconnected graph support in cuGraph

### ISSUE THREAD

**Issue by afender** [rapidsai/cugraph#305]
We need to identify algorithms that do not support disconnected graphs and the reason(s) why.

1. Find a relevant disconnected input and test each feature on it. This dataset should be small enough so that it can be added to the nightly test suite but large enough to capture all potential issues (~ 1,024<V<4,096). Compare the output against NetworkX. 

2. Create a spreadsheet with the following information for each algorithm : 
  - Algorithm 
  - Disconnected support 
  - Reason, if not supported 
  - Proposed solution, if applicable 

3. For all working algorithms: add the disconnected dataset to the nightly test data. 
4. Fill GitHub issues for all algorithms that can be fixed (ie. when this is an implementation issue rather than a theoretical limit)

**Comment by BradReesWork** [comment]
Adding a test file with two disconnected (disjoint) subgraph produced a number of errors.  
This issue is being pushed to 0.16 so that the errors can be fixed:

There is an assumption in tests that there is only 1 largest components, which is no longer true with two disjoint graphs

- test_weak
- test_connectivity
- test_graph (test_consolidation)
