### ISSUE TITLE
[QST]: Improving libcugraph Documentation: A Call for Comprehensive C++ Library Documentation

### ISSUE THREAD

**Issue by lxrzlyr** [rapidsai/cugraph#3353]
### What is your question?

I am writing to express my concerns regarding the documentation for libcugraph. As a user of the library, I have found the existing documentation to be challenging to comprehend and lacking essential details necessary for developing new functions.

While browsing both the repository and the Rapids website, I have observed that a significant portion of the C++ documentation is either unavailable, returning a 404 error, or still under development. Providing comprehensive documentation for the C++ library is crucial to enable users to develop customized functions with ease.

I hope the cugraph maintainers to prioritize the creation and provision of detailed C++ library documentation, as it is in high demand by many users in the community.

Thank you for your attention to this matter.

### Code of Conduct

- [X] I agree to follow cuGraph's Code of Conduct
- [X] I have searched the [open issues](https://github.com/rapidsai/cugraph/issues) and have found no duplicates for this question

**Comment by acostadon** [comment]
We are in the process of redoing all our documentation. There will be some major updates throughout the month of April and beyond. As part of this, we will be releasing a series of how-to guides. If you would like to see a particular function addressed in a dedicated guide, please let us know and we will do our best to include that. 

Also, if you can be specific as to which essential details you need explained, we can prioritize those and make them available to you.

**Comment by lxrzlyr** [comment]
I am currently developing an All-Pairs Shortest Path (APSP) application using cuGraph's Single-Source Shortest Path (SSSP) API. I have encountered a couple of issues during the development process and would appreciate your assistance.

GPU memory issue in Python:
While using Python, I noticed that the GPU memory required by the program keeps increasing. The test graph I am using is of a fixed size, and the calling method is simple. I wrote a loop to call cugraph::sssp. Please refer to the attached Python file for more details.

If this is a code-writing issue, could you please suggest how to release GPU memory? I am not very proficient in Python, and I couldn't find any methods or reminders about releasing GPU memory in the documentation.

Lack of C++ documentation for libcugraph:
Due to the GPU memory issue mentioned above, I decided to switch to libcugraph for developing the APSP application. However, I encountered another problem: I couldn't find any comprehensive C++ documentation for libcugraph.

If you could provide a guide or any resources to help me understand how to call the SSSP function using libcugraph, I would be very grateful. A sample program would be extremely helpful as well.

To reproduce the first issue, please use the attached Python file and the MTX file, Command { python3 NFD.py ./XXX.mtx }. If you require any additional information, please let me know.

Thank you for your assistance.
[file.zip](https://github.com/rapidsai/cugraph/files/11040843/file.zip)

**Comment by ChuckHastings** [comment]
@lxrzlyr Thanks for your interest in interacting with us at the C++ level.  We haven't had many requests for this level of access, so good documentation at that layer has been a lower priority.  As @acostadon indicated, we'll definitely get to work on those improvements.

The best entry point for understanding the code today (while we get better documentation in place) would be to look at the C++ unit tests.  https://github.com/rapidsai/cugraph/blob/393db1d013c56ef3186e013491bed80de1427f58/cpp/tests/traversal/sssp_test.cpp#L114 is the relevant location for the SSSP test.  The creation of the graph occurs in this code: https://github.com/rapidsai/cugraph/blob/393db1d013c56ef3186e013491bed80de1427f58/cpp/tests/utilities/test_graphs.hpp#L618

Key highlights of the C++ code:
* The graph and graph_view are templated by the template parameters vertex_t, edge_t, store_transposed and multi_gpu.  You'll need to instantiate the right version for the algorithm to work.  For SSSP store_transposed should be `false`.  You haven't mentioned using a MG solution, so multi_gpu should be `false`.  If you need multiple GPUs to fit the graph size we can talk about that, but you mention you're using a small graph.
* To conserve GPU memory, you should try to use vertex_t as int32_t and edge_t as int32_t.  Larger types will use more memory, and since you mention that your graph is small you can probably fit in 32-bit integers.
* edge weights were recently split out into a separate class, I'd suggest either using the 23.04 nightlies, or building cugraph yourself from the 23.04 branch.  If you use older versions of cugraph you'll need to update to the new implementation, so it's probably easier to start there.
* If you're only interested in the costs, passing the predecessors as nullptr will save you memory.  As @BradReesWork said, if you want all paths then we don't actually have an algorithm that does that, although we could discuss how to construct one.  Implementing that is on our backlog, but not currently on our road map.
* If you have specific data you want to load, look at this statement: https://github.com/rapidsai/cugraph/blob/393db1d013c56ef3186e013491bed80de1427f58/cpp/tests/utilities/test_graphs.hpp#L625.  This calls a function that will return `rmm::device_uvector` objects containing src, dst, wgt, a list of vertex ids and a boolean indicating whether the data is symmetric or not.  Instead of calling this function you can create the appropriate `rmm::device_uvector` objects and populate them by yourself and set the `is_symmetric` flag appropriately.

**Comment by lxrzlyr** [comment]
Thank you for your assistance in solving my GPU memory usage problem. I was able to resolve the issue by commenting out the relevant storage path commands. I have also realized that storing detailed paths is very memory-consuming, and I generally just focus on the distance matrix. The distance matrix is an extremely dense matrix, and it is a better solution to print it to a file in CSR format while generating it. This means that only one 1D array needs to be maintained in memory.

Regarding the issue of losing a portion of all-paths, I am not sure if you mean to generate a new path by combining the shortest paths with multiple origins. I don't think this is reasonable, since the shortest path doesn't necessarily go through the nodes currently being considered. The general technique is implemented through the parallel SSSP algorithm, and each source node needs to be traversed once. The most advanced and applicable parallel SSSP algorithm may be delta-stepping.

Thank you for providing the C++ examples and function-related documents. They were extremely helpful in my development process.development process.

**Comment by BradReesWork** [comment]
@lxrzlyr how large is your graph?   Here is an example for small graphs:  https://github.com/rapidsai/cugraph/blob/branch-23.04/notebooks/applications/CostMatrix.ipynb

**Comment by lxrzlyr** [comment]
For this problem, I can't provide a rigorous derivation for the time being. I think BFS with a condition may help. This means that other SSSP algorithms need to be used to obtain the length of the shortest path, and then use BFS with a condition to traverse all paths, which will be a highly parallelizable method. It is obvious that the time complexity of BFS with a condition is less than O(E), because it does not visit every edge. At present, I can't determine the specific time complexity. It may need to be calculated by the distribution of shortest path lengths. If you have a paper on the latest achievements of BFS, you can also provide it to us for reference.

This is a shortest path traversal problem that our group has not yet paid attention to. Before that, we focused more on accelerating all-source shortest path computation on graphs over 200k. After careful discussion with the group members, I will give a definitive conclusion. If you continue to investigate this problem further, we will announce the result later.

If you are also very interested in this issue, you can try this method from the code first, and the specific implementation can apply the template of the BFS algorithm. Please also inform me if you get results. Experimental data will help in theoretical calculations.

Thank you for your assistance.

**Comment by acostadon** [comment]
Thanks Chuck for answering this. 
I am closing this question and have created an issue to track the work of adding the relevant documentation to the new cuGraph docs area.

https://github.com/rapidsai/cugraph/issues/3406
