### ISSUE TITLE
Identify primitives necessary to implement K-Truss

### ISSUE THREAD

**Issue by ChuckHastings** [rapidsai/cugraph#3446]
Investigate the K-Truss algorithm.  Identify primitives necessary to provide a MG implementation of K-Truss.

As long as we get comparable performance to the current cuHornet SG implementation, and can process in MG environment, we can leave some gaps for future performance improvement.  The first priority here is to be able to eliminate our dependency on cuHornet.

Upon completion of the investigation we should add tasks to #2167 to implement the proposed primitives.

**Comment by seunghwak** [comment]
My current plan is to use a K-truss algorithm inspired by "R. Pierce and G. Sanders, K-truss decomposition for scale-free graphs at scale in distributed memory, 2018" but using an intersection based approach instead of their wedge based approach to better re-use our existing primitives.

This outlines the algorithm.

1. Check the input graph is symmetric (undirected) and there is no multi-edges (https://github.com/rapidsai/cugraph/blob/branch-23.04/cpp/src/community/triangle_count_impl.cuh#L165).
2. Remove self-loops (https://github.com/rapidsai/cugraph/blob/branch-23.04/cpp/src/community/triangle_count_impl.cuh#L204).
3. Extract K+1 core  (using https://github.com/rapidsai/cugraph/blob/branch-23.04/cpp/include/cugraph/algorithms.hpp#L1787)
4. Convert to a DODG (degree oriented directed graph, https://github.com/rapidsai/cugraph/blob/branch-23.04/cpp/src/community/triangle_count_impl.cuh#L313)
5. Decompress the resulting graph to an edge list (https://github.com/rapidsai/cugraph/blob/branch-23.04/cpp/include/cugraph/graph_functions.hpp#L368).
6. Partition the edge list to chunks to save memory.
6-1. For each partition, find the intersection of edge endpoints' destination neighbors (we have `detail::nbr_intersection`, we need to create a non-detail space wrapper function).
6-2. For each (p, q, intersection of p&q's neighbor lists), we need to create triplets (p,q,intersection_size) and for each vertex r in the intersection (p, r, 1) and (q,r,1).
6-3. Shuffle the edge, value pairs in multi-GPU (https://github.com/rapidsai/cugraph/blob/branch-23.04/cpp/include/cugraph/detail/shuffle_wrappers.hpp#L55)
6-4. Sort and reduce the shuffled triplets (key: edge source & destination, we can use thrust::sort_by_key and thrust::reduce_by_key)
6-5. Find triangle counts for each edge.
7. Run thrust::partition to place the edges with triangle counts smaller than K-2 at the end. These edges should be "unrolled" and removed (unrolled means undoing their contributions to triangle counts, see the Pierce & Sanders for additional details)
8. While (# edges to be remove > 0)
8-1. Find (p, q, intersection of p&q's neighbor lists) for each edge to be removed. For each vertex r in the intersection, enumerate (p,r,-1) and (q,r,-1)
8-2. For each edge to be removed (say (q,r)), find all the incoming edges of q, then query the existence of (p,q) & (p,r) assuming p is an incoming neighbor of q. Accumulate (p,q,-1) and (p,r,-1) if both exists.
8-3. Similarly for each edge to be removed (say (p,r)), find all the outgoing edges of p, then query the existence of (p,q) and (q,r) assuming q is an outgoing neighbor of p. Accumulate (p,q,-1) and (q,r,-1).
8-4. Shuffle similar to 6-3 in multi-GPU.
8-5. Update triangle counts based on triplets (similar to 6-4 & 6-5).
8-6. Mask out the edges to be deleted.
8-7. Identify the new set of edges to be deleted by running thrust::partition again on the edge list based on newly update triangle counts.

There are few missing pieces to implement this.

1) we need to mask out edges (if not, we need to re-create a graph every time we run 8-6).
2) we should query existences (or multiplicity to be used for multi-graphs as well) of edges (we may actually skip this and apply (s,d, delta) only if (s,d) exists).
3) we need a wrapper for detail::nbr_intersection to avoid calling a detail space function (and the caller should partition the edge list in a certain way for this detail space function to be efficient, better not expose this to end users).

[PR #2829](https://github.com/rapidsai/cugraph/pull/2829) is necessary to support edge masking allocating 1 bit per edge (instead of 1 byte per edge).
Then, we need to implement edge masking, and 'detail::nbr_intersection` should be updated to work with edge masking.
The, we need to create a wrapper for `detail::nbr_intersection`.
If we decide to query edge multiplicities, this function should be added as well (and this function should work with edge masking).
Then, we need to implement K-truss.

Truss decomposition can be implemented by successively calling K-truss, but using the K-1-truss graph from the previous iteration as the input graph to find the K-truss graph.
