### ISSUE TITLE
cuGraph benchmark dataset

### ISSUE THREAD

**Issue by Soroushmehr1** [rapidsai/cugraph#3598]
### What is your question?

What are the characteristics (e.g. size, type,..) of the dataset used in cuGraph Benchmarks? 

### Code of Conduct

- [X] I agree to follow cuGraph's Code of Conduct
- [X] I have searched the [open issues](https://github.com/rapidsai/cugraph/issues) and have found no duplicates for this question

**Comment by acostadon** [comment]
Sorry for the delay in answering
This page details all of our datasets. The ones specific to our benchmarks are at the bottom
https://github.com/rapidsai/cugraph/blob/branch-23.08/datasets/README.md

We also use synthetic data in order to more precisely scale.
Many of our benchmarks like this notebook run synthetic data:
https://github.com/rapidsai/cugraph/blob/branch-23.08/notebooks/cugraph_benchmarks/synth_release.ipynb

here is a link to the API for the synthetic data generator.
https://docs.rapids.ai/api/cugraph/nightly/api_docs/api/cugraph/cugraph.generators.rmat/#cugraph.generators.rmat

hope this helps
