### ISSUE TITLE
Update Louvain args for some level of compatibility with NetworkX

### ISSUE THREAD

**Issue by rlratzel** [rapidsai/cugraph#3700]
For supporting the use of pylibcugraph as a backend to NetworkX for Louvain, we need to ensure that a NetworkX Louvain call can be mapped to an equivalent PLC Louvain call.  

This doesn't require a 1:1 mapping of args, and some level of translation is acceptable assuming there's no significant performance impact.

One immediate issue is the `threshold` arg for Nx Louvain ([here](https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.community.louvain.louvain_communities.html)) which PLC Louvain has no equivalent.

cc @ChuckHastings

**Comment by ChuckHastings** [comment]
We currently don't expose that parameter, it's hardcoded in the C++ implementation.  We can easily expose that as a parameter through the code stack, we'll need to define C++ issues.

Tangentially related, if we're going to change Louvain arguments, I'd like to make the pitch (I think I made this casually a few years ago and we didn't do anything) to change the name of the parameter `max_iter`.  My suggestion would be `max_level` instead.  Some explanation...

Louvain is a hierarchical clustering algorithm.  As such, there are two types of iteration in Louvain.  First there is iteration of the basic optimization algorithm.  We execute the Louvain approach to estimate maximum modularity for a given graph.  This runs until convergence.  The `threshold` parameter proposed here would allow the user to define how close we need to get for convergence.  The nature of the way this algorithm is defined we are guaranteed to converge (unlike some algorithms like PageRank and Katz).

The second type of iteration is the hierarchical part.  After we execute the Louvain approximation on the original graph, we coarsen the graph by consolidating all vertices in the same cluster into a coarsened vertex and create a new collection of edges by combining edges between the same coarsened vertices into a coarsened edge.  We then repeat the Louvain approach to estimate maximum modularity described above.

The parameter that's defined as `max_iter` at the python layer is actually mapped to a parameter in the C API called `max_level` (and, carelessly, at the C++ API called `max_depth`).  This parameter controls the number of hierarchical iterations that we do.  If `max_level` is 1 then we just do the Louvain approximation on the original graph and stop.  If `max_level` is `k` then we do at most `k` iterations of the Louvain approximation, doing a graph coarsening step in between.

I don't see a Louvain implementation in any of the packages out there (although I did a casual search) that exposes this `max_level` parameter (or a `max_iter` parameter).

I'd like to see us change the python, C API and C++ code to use the same name for the parameter, it will be less confusing.  I'm personally leaning toward `max_level`, but could be convinced otherwise.  I think `max_iter` is a bad label, as it suggests a maximum number of iterations on the Louvain approximation step (the thing most like PageRank).  This is, in fact, wrong.  We could talk about also adding a parameter to control this, but understanding how to set that would require knowledge of how the up/down optimization works, which is probably beyond what we want to expose to our users.

**Comment by rlratzel** [comment]
PR https://github.com/rapidsai/cugraph/pull/3792 is up which addresses some or all of this

**Comment by rlratzel** [comment]
@eriknw noticed NetworkX supports Louvain for undirected and directed, but cugraph only supports it for undirected.

**Comment by ChuckHastings** [comment]
Interesting.  The NX Louvain documentation references a paper I had not yet seen that discusses how to do Louvain on a directed graph.  I'll need to review the paper.  For now we will need to restrict using cugraph to the undirected case.  We can add the directed case to the backlog and plan it into a road map.

**Comment by rlratzel** [comment]
Agreed. It's acceptable to have a backend only partially support a Nx API, and we have the ability to properly raise `UnsupportedError` exceptions for specific combinations of inputs, so this would be one of them.

**Comment by rlratzel** [comment]
PR #3792 closes this.
