### ISSUE TITLE
[FEA] Shift MFG (Renumbering and CSC) Creation from Training to Sampling GPUs

### ISSUE THREAD

**Issue by VibhuJawa** [rapidsai/cugraph#3703]
At present, our system leverages training GPUs for various operations, including the creation of MFG (Renumbering and COO), feature fetching, and training. However, we recognize that our sampling GPUs >> training GPUs (8x more often). 

To optimize our performance, I propose we shift the MFG (Renumbering and COO) creation tasks to the sampling GPUs. This change is expected to significantly enhance our operational speed and efficiency.

We will need to frame-work specific renumbering for `PyG` and `DGL` and scope the needed changes for it. 

CC: @alexbarghi-nv , @seunghwak , @tingyu66

**Comment by VibhuJawa** [comment]
CSC creation logic to prevent doing:  

https://github.com/rapidsai/cugraph/blob/037239686052ee4e07286dcf235d0aa1b0da0ff0/python/cugraph-dgl/cugraph_dgl/nn/conv/sageconv.py#L125

**Comment by tingyu66** [comment]
@VibhuJawa The cugraph-ops conv layers can take in either an MFG or a regular graph. For an MFG with $m$ source (input) nodes and $n$ destination (output) nodes, the source node ids `g.srcnodes()` need to be `torch.arange(m)` and destination nodes ids `g.dstnodes()` should be `torch.arange(n)`.

Since in dgl source nodes list always includes destinations nodes by default, `g.dstnodes()` should be the same as `g.srcnodes()[:g.num_dst_nodes()]`.

**Comment by VibhuJawa** [comment]
DGL Example of requested renumbering. 

```python3
>>> import dgl
>>> g = dgl.graph(([30,40,50,60], [10,10,20,20]))
>>> frontier = g.sample_neighbors(nodes=[10,20],fanout=2)

>>> frontier
Graph(num_nodes=61, num_edges=4,
      ndata_schemes={}
      edata_schemes={'_ID': Scheme(shape=(), dtype=torch.int64)})
>>> frontier.edges()
(tensor([40, 30, 60, 50]), tensor([10, 10, 20, 20]))

>>> block = dgl.to_block(frontier,[10,20])
>>> block.edges()
(tensor([2, 3, 4, 5]), tensor([0, 0, 1, 1]))

>>> block.srcnodes()
tensor([0, 1, 2, 3, 4, 5])
>>> block.dstnodes()
tensor([0, 1])
```

So I guess from an **ask** perspective the ask is to `renumber` the `samples`  per `hop` , so that `destinations` are renumbered in a increasing order of range `0-n` and `sources` are renumbered to be `0-m` , where `m` includes `destinations` (`or n`)

 
 CC: @tingyu66 , Can you confirm if above looks good to you.

**Comment by tingyu66** [comment]
> DGL Example of requested renumbering.
> 
> ```python
> >>> import dgl
> >>> g = dgl.graph(([30,40,50,60], [10,10,20,20]))
> >>> frontier = g.sample_neighbors(nodes=[10,20],fanout=2)
> 
> >>> frontier
> Graph(num_nodes=61, num_edges=4,
>       ndata_schemes={}
>       edata_schemes={'_ID': Scheme(shape=(), dtype=torch.int64)})
> >>> frontier.edges()
> (tensor([40, 30, 60, 50]), tensor([10, 10, 20, 20]))
> 
> >>> block = dgl.to_block(frontier,[10,20])
> >>> block.edges()
> (tensor([2, 3, 4, 5]), tensor([0, 0, 1, 1]))
> 
> >>> block.srcnodes()
> tensor([0, 1, 2, 3, 4, 5])
> >>> block.dstnodes()
> tensor([0, 1])
> ```
> 
> So I guess from an **ask** perspective the ask is to `renumber` the `samples` per `hop` , so that `destinations` are renumbered in a increasing order of range `0-n` and `sources` are renumbered to be `0-m` , where `m` includes `destinations` (`or n`)
> 
> CC: @tingyu66 , Can you confirm if above looks good to you.

Yes the example looks good. We basically need the same renumbering strategy as in to_block.

**Comment by VibhuJawa** [comment]
`to_block` logic here: 
https://github.com/dmlc/dgl/blob/09e5aa961dac1b8ea196e2a54e0a85a724b6a8a9/src/graph/transform/cuda/cuda_to_block.cu#L91-L101

**Comment by VibhuJawa** [comment]
Notebook to showcase bottleneck: https://gist.github.com/VibhuJawa/a3967ff38a8b6dad8f89dda7a61182e2

**Comment by tingyu66** [comment]
To follow up the discussion with @VibhuJawa, I think we only need to renumber once after gathering sampling results to create multiple dgl blocks.
We can simply sort the sampled nodes based on the hop id, namely, the furthest distance of a node away from the first layer, so that the arange requirements of node ids for each block is naturally satisfied. In this toy example:
```
    hop1       hop2
a -------- b  --------  c 
b          c
c
```
distance: c > b > a, so `[a,b,c]` should be renumbered as `[2,1,0]`. The `g.srcnodes()` and `g.dstnodes()` of each block are `arange()` values.

**Comment by seunghwak** [comment]
Should I maintain the order in @ edgelist_srcs and @edgelist_dsts in return values?

**Comment by VibhuJawa** [comment]
> Should I maintain the order in @ edgelist_srcs and @edgelist_dsts in return values?

FWIW on the Python side, We rely on edge ids to be contiguous (per batch and per hop), as long as that is satisfied i dont think we care about the order inside a hop.
