### ISSUE TITLE
[FEA] Deploy libnvgraph.so

### ISSUE THREAD

**Issue by afender** [rapidsai/cugraph#429]
- [x] Rename repo and make public
- [x] Document how to build from source and add libnvgraph.so into the cuda lib folder
- [x] Wite the process for bug and issues handling
- [x] Consider deploying binaries (won't happen unless )

**Comment by afender** [comment]
Done. The blog post for the announcement is being reviewed.

**Comment by afender** [comment]
@jwyles since you are familiar with nvGraph, can you help me by reviewing the repo and maybe try to build/install on your machine: https://github.com/rapidsai/nvgraph

**Comment by jwyles** [comment]
I have been looking at the repo and it looks good. A couple things that might be nice: It says in README.md that the documentation for the C api can be found in the cuda toolkit documentation, since it will be removed from there when nvgraph is dropped it should probably be moved into the repo somewhere. Second, there aren't instructions for getting the datasets to run the tests, that would be nice as well. Also, when I was running the tests there were a bunch of failures, most of which look to be due to not found datasets, but some don't. For example triangle count is getting the wrong result and not complaining about a missing file...

**Comment by jwyles** [comment]
After looking some more it appears that the only test failure is in the triangles test. I think the reference results may need to be updated, since after fixing triangle counting to match networkX we don't get the same results anymore.

**Comment by afender** [comment]
> It says in README.md that the documentation for the C api can be found in the cuda toolkit documentation, since it will be removed from there when nvgraph is dropped it should probably be moved into the repo somewhere.

Yup, I thought about that as well. The link point to the permanent link to CUDA 10.0 archive version (which will still be available after nvgrpah is dropped from the toolkit).

> there aren't instructions for getting the datasets to run the tests, that would be nice as well [...] I think the reference results may need to be updated, since after fixing triangle counting to match networkX we don't get the same results anymore.

Good catch. While exposing the complete test suite would be ideal, it was primarily designed for an internal testing environment and properly porting it would be a significant amount of work. For now, we will build only a minimal set of stand-alone tests that check that the library was properly built.

**Comment by afender** [comment]
Updated readme and the cmake file for tests
