### ISSUE TITLE
[BUG]:  cugpraph_ops error

### ISSUE THREAD

**Issue by yigithanyigit** [rapidsai/cugraph#4826]
### Version

24.10

### Which installation method(s) does this occur on?

Conda

### Describe the bug.

Same with #4763. FYI.

### Code of Conduct

- [x] I agree to follow cuGraph's Code of Conduct
- [x] I have searched the [open bugs](https://github.com/rapidsai/cugraph/issues?q=is%3Aopen+is%3Aissue+label%3Abug) and have found no duplicates for this bug report

**Comment by ChuckHastings** [comment]
The fix for the bug you reported in #4736 is included in version 24.12.  We generally don't back-port bug fixes related to building code in different environments into older releases.

You can access the 24.12 nightlies from this location: https://anaconda.org/rapidsai-nightly.  The official release of 24.12 is coming up, I think next week.
