### ISSUE TITLE
[FEA] Fix and Add triangle counting

### ISSUE THREAD

**Issue by afender** [rapidsai/cugraph#52]
The first step is to add the C++ code to access nvgraph TC features when using cugraph graph structure.  Since Triangle Counting code is quite self-contained, it can be refactored to get rid of nvgraph dependencies and moved inside cugraph. In this case, the CUDA code needs to be updated to support RMM. Alternatively, it is possible to just add a C++ driver in cugraph to call nvgraph API by using the helper functions provided in `nvgraph_gdf.cu`.

The second step consists of adding python bindings for the TC feature

Subtasks checklist for python:

- [ ]  Python bindings and API (may include some adjustments of the C++/CUDA part)
- [ ]  Pytest testing against NetworkX
- [ ]  Documentation
     - [ ]  Doxygen (C++)
     - [ ]  Sphinx (Python)
     - [ ]  python code example
- [ ]  Check headers and licenses
- [ ]  Validate everything in Jenkins

**Comment by jwyles** [comment]
Bindings are done with nvgraph wrapper. Decision was made to wait until we import the code into cugraph to release, since there was a bug that needed fixing in nvgraph and the results of nvgraph's triangle counting do not match NetworkX for all graphs.

**Comment by afender** [comment]
Moving back to the backlog.

**Comment by seunghwak** [comment]
I rebased today and pytest is failing for triangle count.

Based on James's comments, it seems like this is a known issue (and fixed in PR #220), but it is failing in my system, and any thoughts?

<pre>
================================================== FAILURES ==================================================
_________________________________ test_triangles[../datasets/netscience.mtx] _________________________________

graph_file = '../datasets/netscience.mtx'

    @pytest.mark.parametrize('graph_file', DATASETS)
    def test_triangles(graph_file):
        M = read_mtx_file(graph_file)
        cu_count = cugraph_call(M)
        nx_count = networkx_call(M)
>       assert cu_count == nx_count
E       assert 11450 == 11292

cugraph/triangle_count/test_triangle_count.py:68: AssertionError
-------------------------------------------- Captured stdout call --------------------------------------------
Reading ../datasets/netscience.mtx...
_____________________________ test_triangles_edge_vals[../datasets/dolphins.mtx] _____________________________

graph_file = '../datasets/dolphins.mtx'

    @pytest.mark.parametrize('graph_file', DATASETS)
    def test_triangles_edge_vals(graph_file):
        M = read_mtx_file(graph_file)
>       cu_count = cugraph_call(M, edgevals=True)

cugraph/triangle_count/test_triangle_count.py:74: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
cugraph/triangle_count/test_triangle_count.py:46: in cugraph_call
    return cugraph.triangles(G)
cugraph/triangle_count/triangle_count_wrapper.pyx:22: in cugraph.triangles
    cpdef triangles(input_graph):
cugraph/triangle_count/triangle_count_wrapper.pyx:55: in cugraph.triangles
    cudf.bindings.cudf_cpp.check_gdf_error(err)
cudf/bindings/cudf_cpp.pyx:237: in cudf.bindings.cudf_cpp.check_gdf_error
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   cudf.bindings.GDFError.GDFError: b'GDF_INVALID_API_CALL'

cudf/bindings/cudf_cpp.pyx:255: GDFError
-------------------------------------------- Captured stdout call --------------------------------------------
Reading ../datasets/dolphins.mtx...
______________________________ test_triangles_edge_vals[../datasets/karate.mtx] ______________________________

graph_file = '../datasets/karate.mtx'

    @pytest.mark.parametrize('graph_file', DATASETS)
    def test_triangles_edge_vals(graph_file):
        M = read_mtx_file(graph_file)
>       cu_count = cugraph_call(M, edgevals=True)

cugraph/triangle_count/test_triangle_count.py:74: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
cugraph/triangle_count/test_triangle_count.py:46: in cugraph_call
    return cugraph.triangles(G)
cugraph/triangle_count/triangle_count_wrapper.pyx:22: in cugraph.triangles
    cpdef triangles(input_graph):
cugraph/triangle_count/triangle_count_wrapper.pyx:55: in cugraph.triangles
    cudf.bindings.cudf_cpp.check_gdf_error(err)
cudf/bindings/cudf_cpp.pyx:237: in cudf.bindings.cudf_cpp.check_gdf_error
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   cudf.bindings.GDFError.GDFError: b'GDF_INVALID_API_CALL'

cudf/bindings/cudf_cpp.pyx:255: GDFError
-------------------------------------------- Captured stdout call --------------------------------------------
Reading ../datasets/karate.mtx...
____________________________ test_triangles_edge_vals[../datasets/netscience.mtx] ____________________________

graph_file = '../datasets/netscience.mtx'

    @pytest.mark.parametrize('graph_file', DATASETS)
    def test_triangles_edge_vals(graph_file):
        M = read_mtx_file(graph_file)
>       cu_count = cugraph_call(M, edgevals=True)

cugraph/triangle_count/test_triangle_count.py:74: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
cugraph/triangle_count/test_triangle_count.py:46: in cugraph_call
    return cugraph.triangles(G)
cugraph/triangle_count/triangle_count_wrapper.pyx:22: in cugraph.triangles
    cpdef triangles(input_graph):
cugraph/triangle_count/triangle_count_wrapper.pyx:55: in cugraph.triangles
    cudf.bindings.cudf_cpp.check_gdf_error(err)
cudf/bindings/cudf_cpp.pyx:237: in cudf.bindings.cudf_cpp.check_gdf_error
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   cudf.bindings.GDFError.GDFError: b'GDF_INVALID_API_CALL'

cudf/bindings/cudf_cpp.pyx:255: GDFError
</pre>

**Comment by jwyles** [comment]
@seunghwak It looks like you need to rebuild and install nvgraph. The results you are getting look like they are the results from the pre-fix nvgraph. Nvgraph doesn't automatically rebuild so you need to do it manually when it's updated.

**Comment by seunghwak** [comment]
@jwyles Thanks, and rebuilding under cugraph/cpp/nvgraph/cpp/build fixed the problem... My remaining concern is that cuGraph's main README.md file (https://github.com/rapidsai/cugraph/blob/branch-0.7/README.md) says

```
This project uses cmake for building the C/C++ library. CMake will also automatically build and install nvGraph library ($CUGRAPH_HOME/cpp/nvgraph) which may take a few minutes. To configure cmake, run:
```

But it seems like deleting everything in the main build directory (cugraph/cpp/build), and running cmake; make; make install from scratch is not sufficient to properly install nvgraph... but I guess this should be a separate issue.
