### ISSUE TITLE
[FEA] ASSP problem

### ISSUE THREAD

**Issue by cy69855522** [rapidsai/cugraph#529]
**Is your feature request related to a problem? Please describe.**
Thanks to share this wonderful repo, but I'm always frustrated when no support for sparse graph all source shortest problem(ASSP), I want to get the path information for all nodes. (Ex. a->b->c->d or a Path matrix) ::>_<::

**Describe the solution you'd like**
Johnson gpu implementation

**Comment by iceboy910447** [comment]
I'm currently working with several street network graphs of New York City, with up to 250.000 nodes and 500000 edges. Since a matrix for ASSP for a graph that size would exceed the memory capacity of most of the graphic cards available today, would it be possible to add a function that instead allows use a cudf.series of starting vertex id's as an input? This way the efficiency of calculating sssp for multiple nodes could be improved with a parallel approach (as mentioned in  [https://github.com/rapidsai/cugraph/issues/1339](url) ), since in my case a simple loop approach only lead to a gpu utilization of 60%. It also would help to stay within a memory capacity limit. I will try to provide a simple jupyter notebook with an example within the next couple of days. 

Thanks
iceboy

**Comment by rewaza** [comment]
I'm trying to get a list of nodes like APSP (all pairs short path) and want to use rapids cugraph for GPU acceleration. Created this script which is working but it's very slow. I suppose I'm doing the wrong iteration and there could be a better way to achieve the same result faster. Am I on the wrong way? Thank you!

```
import sqlalchemy
import cugraph
import cudf
import pandas as pd
from datetime import datetime

s_time = datetime.now()
engine = sqlalchemy.create_engine('postgresql://postgres:xxxxxxx@localhost:5432/postgres')
sql = "select id, source, target, cost, geom from xxx.roads_noded"
rc = "select source, target from xxx.routin_candidates"
df = pd.read_sql(sql, engine)
rcdf = pd.read_sql(rc, engine)
cuda_g = cudf.DataFrame.from_pandas(df)
cuda_nc = cudf.DataFrame.from_pandas(rcdf)

G = cugraph.Graph()
G.from_cudf_edgelist(cuda_g, source='source', destination='target', edge_attr='cost')

for index, row in cuda_nc.to_pandas().iterrows():
    src = row['source']
    dest = row['target']
    routes = cugraph.sssp(G, src)
    for index, row in routes.to_pandas().iterrows():
        v = int(row['vertex'])        
        if v == dest:
            p = cugraph.utils.get_traversed_path_list(routes, v)
            autoroute = p[::-1]
            print(autoroute)

e_time = datetime.now()
print('Duration: {}'.format(e_time - s_time))
```

**Comment by BradReesWork** [comment]
closing and creating a new issue
