### ISSUE TITLE
[BUG] Add README.md install instructions for nvgraph plugin, or link to external instructions

### ISSUE THREAD

**Issue by randerzander** [rapidsai/cugraph#55]
See title

**Comment by afender** [comment]
Nvgraph is released as a conda packadge : https://anaconda.org/nvidia/nvgraph
It can be manually installed using: conda install -c nvidia nvgraph 

PR #42 added nvgraph to the conda env file so that there is no need for specific instructions or readme for nvgraph. However, this PR cannot be merged because the nvgraph conda packadge is currently outdated.

**Comment by randerzander** [comment]
No longer relevant
