### ISSUE TITLE
[BUG] wrong edge count using nightly builds 

### ISSUE THREAD

**Issue by dorisnvidia** [rapidsai/cugraph#613]
**Describe the bug**
A customer reported and I confirmed that add_edge_list gives a strange warning and the edge count of the graph is incorrect, when using either rapidsai-dev-nightly:0.11-cuda10.x-devel-xx containers or rapidsai-nightly:cuda10.x-runtime-xx containers 

The stable builds are correct, i.e., rapidsai:cuda10.x-runtime-xxx

**To Reproduce**
docker pull rapidsai/rapidsai-nightly:cuda10.0-runtime-centos7
docker run --gpus all --rm -it -p 8888:8888 -p 8787:8787 -p 8786:8786 rapidsai/rapidsai-nightly:cuda10.0-runtime-centos7

Python code:
import cugraph
import cudf
import numpy as np

gdf = cudf.DataFrame()
gdf["src"]=[1, 1, 1, 1, 2, 2, 2, 3, 3]
gdf["src"]=gdf["src"].astype('int32')
gdf["dst"]=[5, 6, 7, 8, 5, 6, 7, 4, 8]
gdf["dst"]=gdf["dst"].astype('int32')

gdf["src"] = gdf["src"] - 1
gdf["dst"] = gdf["dst"] - 1

G = cugraph.Graph()
G.add_edge_list(gdf["src"], gdf["dst"], None)

print("\tNumber of Vertices: " + str(G.number_of_vertices()))
print("\tNumber of Edges:    " + str(G.number_of_edges()))

**Expected behavior**
Below should be the correct behavior. 
No warning after G.add_edge_list line. and the printout:
        Number of Vertices: 8
	Number of Edges:    9

**Screenshots**
see attached cugraph.png for incorrect behavior 
![cugraph](https://user-images.githubusercontent.com/43153139/70069986-5906b900-15b8-11ea-8c0f-7c46873d71d7.PNG)

**Desktop (please complete the following information):**
 - OS: centos7. running on a V100 node on PSGcluster

**Comment by BradReesWork** [comment]
Thanks for reporting this.  We are looking into the issue

**Comment by afender** [comment]
Thank you, Doris. 
You customer is experiencing what is described here https://github.com/rapidsai/cugraph/issues/603

**Comment by dorisnvidia** [comment]
I see, thank you Brad and Alex. So we need to use Digraph() instead of Graph() for directed network graph then.

**Comment by afender** [comment]
The Python API now has `Graph` (undirected) and `DiGraph` (directed).

If your customer is trying to load a directed edge list she should use a `DiGraph`. In this case, cuGraph will return `9` for the number of edges.

If your customer is trying to load an undirected edge list, cuGraph will "symmetrize" it: each undirected edge (u,v) will be stored as two directed edges (u,v) and (v,u). This is why you see `18` as the number of edges currently. This is a detail that will be hidden to the user soon (early 0.12 with more details on that in #603).  

The warning is legit. Users are encouraged to use `from_cudf_edge_list` instead of `add_edge_list` (starting in 0.11).

**Comment by BradReesWork** [comment]
marking as closed.  Please let us know is the issue persists or answer does not address customer's question
