### ISSUE TITLE
[BUG] WCC returns incorrect results on small graphs

### ISSUE THREAD

**Issue by BradReesWork** [rapidsai/cugraph#690]
Calling WCC on a small graph returns incorrect results.

See notebook - https://github.com/dorisnvidia/notebooks-1/blob/branch-0.11-jda-doris/cugraph/supplyChain/ArijitFileExample.ipynb

The user expects the components from the second test to be numbered from 1 and 2, not 1 and 3.

**Comment by ChuckHastings** [comment]
Couple of comments:

1. It would be helpful if the bug description included what the expected output is.  There are two runs in the notebook that I see, which one is incorrect?  I can run networkx against the data and try and ascertain that, but if we know what the expected output is it would be helpful to have it included here.
1. The second data file appears to be missing (when I clone this repo and run the example, it doesn't find the file ../data/Arijit2.csv

**Comment by ChuckHastings** [comment]
The missing test file that generates this error is attached (rename to csv to match notebook code)

[Arijit2.txt](https://github.com/rapidsai/cugraph/files/4156509/Arijit2.txt)

**Comment by ChuckHastings** [comment]
@BradReesWork - Not sure if we want to consider this a code bug, a documentation bug or a misunderstanding of the expected behavior.

`wcc = cugraph.weakly_connected_components(gpuG)` returns a dataframe that contains a column `labels` which is the labels which were assigned by the weakly connected components algorithm.  In our implementation (the conventional approach for WCC), we assign the smallest vertex id contained in the component.

Traditionally there is no notion of ordering in the components of a graph.  The networkx documentation for weakly connected components (from this page: https://networkx.github.io/documentation/stable/reference/algorithms/generated/networkx.algorithms.components.weakly_connected_components.html#networkx.algorithms.components.weakly_connected_components) suggests sorting the components by size as a reasonable thing to do with the output:

```>>> G = nx.path_graph(4, create_using=nx.DiGraph())
>>> nx.add_path(G, [10, 11, 12])
>>> [len(c) for c in sorted(nx.weakly_connected_components(G),
...                         key=len, reverse=True)]
[4, 3]```

As such, it's not clear what a **correct** ordering of the components would actually be.

I'm inclined to say that this is not a bug and that weakly connected components does not work like this.  There is no requirement that the labels assigned to the components must be sequential numbers from 1 to k, they are arbitrary labels.  If the user wants to number them then they should get the list of labels in whatever order they like and use this index as the component number - not the assigned label.

**Comment by jeaton32** [comment]
Totally agree with Chuck.  The components don't have a canonical ordering
returned from WCC.  The user is free to impose something if they find it
useful, but that is outside the definition of what WCC does.

**Comment by BradReesWork** [comment]
marking as closed and adding an issue to update documentation
