### ISSUE TITLE
[BUG] pandas category has no null count

### ISSUE THREAD

**Issue by geoHeil** [rapidsai/cugraph#709]
**Describe the bug**
Columns of pandas category cause creation of graph to fail

**To Reproduce**

```python
df_small = pd.DataFrame({'src':[1,2], 'dst':[2,1], 'weight':[0.2, 0.4], 'attr_1':['foo', 'bar']})
df_small['attr_1'] = df_small['attr_1'].astype('category')
display(df_small)
print(df_small.dtypes)

G = cugraph.MultiGraph()
G.from_cudf_edgelist(df_small, source='src', destination='dst', edge_attr=['weight', 'attr_1'])
```

fails with:

```
AttributeError: 'Series' object has no attribute 'null_count'
```

Version is the current released 0.12 rapidsai package

Additionally, on a larger data set (I still need to figure out to find a reproducible example):

```
   2720                 df[name] = column.build_categorical_column(
   2721                     categories=dtype.categories,
-> 2722                     codes=cat_codes.get(name + "_codes", col),
   2723                     mask=col.mask,
   2724                     ordered=dtype.ordered,

TypeError: unsupported operand type(s) for +: 'int' and 'str'
```

graph creation fails here if a category column is present with zip codes i.e. things which could be numeric most of the time.

**Comment by BradReesWork** [comment]
I updated your code to first convert from Pandas to cuDF, then ran the graph algorithm.

```
gdf = cudf.from_pandas(df_small)
G = cugraph.Graph()
G.from_cudf_edgelist(gdf, source='src', destination='dst', edge_attr=['weight', 'attr_1'])
```

The issue is that you are hitting code that is still under development. Having multiple edge weights is part of the Multigraph work which will be release in either 0.13 or 0.14.   The error you see if that the code is trying to access an arrow function on a list rather than a column.
