### ISSUE TITLE
[BUG] python tests: missing, fail, take very long, and generate warnings.

### ISSUE THREAD

**Issue by seunghwak** [rapidsai/cugraph#80]
**cugraph/jaccard/test_jaccard.py**
Aborted (core dumped)

**cugraph/grmat & cugraph/nvgraph**
no test

**cugraph/luvain, cugraph/pagerank, & cugraph/sssp**
deprecated API warning

**cugraph/graph/test_graph.py**
take very long (#83)

====================================== warnings summary =======================================
/home/seunghwak/Program/anaconda3/envs/cugraph_dev/lib/python3.7/site-packages/yaml/constructor.py:126: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
if not isinstance(key, collections.Hashable):

-- Docs: https://docs.pytest.org/en/latest/warnings.html

**Comment by afender** [comment]
Is this an output from the testing platform or your own machine? Tests are passing for me (latest version in branch-0.6). I believe @aschaffer and @jwyles successfully ran these tests very recently as well. Please add more details about how you ran it and work with the team to identify what was different in your run.

Other than that, I'd agree that Python tests take too long to run. This is because we run NextworkX to compare the result against it. It would be good to find a way to reduce the time of these tests.

**Comment by aschaffer** [comment]
Is this a regression? Tests "take very long" compared to what baseline? (we don't really have perf tests yet, afaik).

**Comment by seunghwak** [comment]
> Is this a regression? Tests "take very long" compared to what baseline? (we don't really have perf tests yet, afaik).

I assumed the purpose of this test is to really assure that all the parts are properly installed and working, and for this purpose, I think the test should finish in minutes or less. I will rerun the test to get exact timing but as I remember this took around 20-30 minutes... Users will think something is wrong if tests take this long.

**Comment by afender** [comment]
There are really 2 different topics here :
1) make python tests run faster 
2) errors and warning in @seunghwak's tests 

Both need to be addressed. I will create another task for (1) and let's keep track of (2) in this issue.
