### ISSUE TITLE
[FEA] SSSP with cutoff

### ISSUE THREAD

**Issue by davidpitl** [rapidsai/cugraph#843]
SSSP function does not allow you to specify the maximum path length, or cutoff, to stop calculation.

similar to NetworkX function param:
https://networkx.github.io/documentation/stable/reference/algorithms/generated/networkx.algorithms.shortest_paths.unweighted.single_source_shortest_path.html#networkx.algorithms.shortest_paths.unweighted.single_source_shortest_path

**Comment by davidpitl** [comment]
Additionally, it may be optional for the SSSP function to return the entire sortest path information in df[predecessor]. Sometimes only df[vertex] and df[distance] is needed. df[predecessor] requires huge amounts of memory for very large graphs.

**Comment by seunghwak** [comment]
https://github.com/networkx/networkx/blob/e5ea3274192cf0c1568f868a8e0db7587f19f9e9/networkx/algorithms/shortest_paths/unweighted.py#L16

cutoff in networkx is for unweighted graph (in this case SSSP is BFS), and for general SSSP with weighted graphs, I think cutoff should be the maximum path distance instead of what NetworkX currently does.

Let me know if I am misunderstanding your request.

**Comment by davidpitl** [comment]
Given a starting point in a graph, with or without weights, what I need is to find all the shortest paths with length below a given threshold or cutoff. 

I don't mean calculating all the paths and then filtering by distance. This task is too long for large graphs. It's to stop the search, within the algorithm, because there are no longer shortest paths below the maximum distance.

As I said in a later comment, additionally, it may be optional for the SSSP function to return the entire sortest path information in df[predecessor]. Sometimes only df[vertex] and df[distance] is needed and df[predecessor] requires huge amounts of memory for very large graphs.

I don't know if I'm understanding your question.

**Comment by seunghwak** [comment]
I think we are on the same page if the length here is the sum of edge weights in the shortest path (instead of the number of edges in the shortest path).

The actual algorithm is not Dijkstra (as this has limited parallelism), but in case of Dijkstra, if the popped vertex from the priority queue has the distance larger than the cutoff, this algorithm will stop.

Skipping df[predecessor] should not be hard.

**Comment by davidpitl** [comment]
Ok perfect. I was always thinking about using Dijkstra's algorithm with 
edge weights.

No problem with df[predecessor]. Just a suggestion for large graphs.

**Comment by pgera** [comment]
An additional qualifier that you need is that for cut-offs, the weights need to be non-negative. With that in place, in theory a delta stepping SSSP could implement cutoffs. The Bellman Ford version is not suitable for cut-offs though. BFS based cutoff (similar to Networkx) should be straightforward.

**Comment by seunghwak** [comment]
I am actually implementing the Near-Far Pile method in A. Davidson, S. Baxter, M. Garland, and J. D. Owens, "Work-efficient parallel GPU methods for single-source shortest paths," 2014.

I haven't really validated this, but I think cutoff will work if I skip pushing the vertex to the queue if the new distance is not smaller than cutoff (as "distance no smaller than cutoff" + weight cannot be smaller than cutoff if weight is nonnegative).

See
https://github.com/rapidsai/cugraph/pull/838/files#diff-733b976fcc27eed40c62264e97834b83R183-R190

**Comment by BradReesWork** [comment]
Closing issues.  We are workign on a re-implementation of SSSP and this request is captured in that refactoring
